# Generated by Django 5.2.7 on 2025-10-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Expense',
        ),
    ]
