# Generated by Django 5.2.7 on 2025-10-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20),
        ),
    ]
