# Generated by Django 5.2.7 on 2025-10-05 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2025, 10, 5)),
        ),
    ]
